/* eslint-disable no-restricted-globals */

// Precaches the app shell (JS/CSS/HTML) built by react-scripts so the app
// loads and runs offline after the first visit — this is a single-page app
// with all learning content bundled into the JS, so shell caching alone is
// enough for full offline use.
import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// self.__WB_MANIFEST is injected by workbox-webpack-plugin at build time
// with the list of files (and hashes) generated by the production build.
precacheAndRoute(self.__WB_MANIFEST);

// Client-side routed SPA: serve the cached index.html for any navigation
// request that isn't a direct asset request (React Router handles the rest).
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Runtime cache for icons/images referenced outside the precache manifest.
registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(?:png|jpg|jpeg|svg|gif|ico)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 60 })],
  })
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
